### ISSUE TITLE
Not able to install PRT using Power Apps CLI

### ISSUE THREAD

**Issue by chinuVymo1997** [microsoft/powerplatform-build-tools#617] opened 2023-11-08 09:13 UTC
ChinmayMahajan@VYMO-IT-LPT-563 ~ % pac tool prt
Microsoft PowerPlatform CLI
Version: 1.28.3+g4ba7dfd
Online documentation: https://aka.ms/PowerPlatformCLI
Feedback, Suggestions, Issues: https://github.com/microsoft/powerplatform-build-tools/discussions

Error: Not a valid command. Try running 'pac [command] help'.

Hints: 
  Parse failed on:            prt
  Current command:            tool
  Is this a known command?    No, was it misspelled?
  Is this a known argument?   No, was it misspelled?
  Was it quote wrapped?       No, be sure to wrap values that contain spaces.

I am getting this error while installing PRT using pac tool. Please help

**Comment by tehcrashxor** [comment] 2023-11-08 22:35
Which operating system are you running that command on?  
If you run `pac tool help`, what output do you see?

Most of the tools within `pac tool ...` are Windows-only due to being WPF applications on net48 or earlier, and are thus not present when running on Linux or Mac.  I can repro that error exactly when running on Linux, but it works as expected on my Windows box, and `pac tool help` shows that the `prt` (and `cmt` and `pd`) commands do not exist when on the Linux box.

**Comment by petrochuk** [comment] 2023-11-09 21:42
Duplicate of https://github.com/microsoft/powerplatform-build-tools/discussions/616

**Closed by petrochuk** 2023-11-09 21:42 UTC
