### ISSUE TITLE
Pac auth create failed if clientsecret contain dash sign at the start

### ISSUE THREAD

**Issue by hoangducdev** [microsoft/powerplatform-build-tools#989] opened 2024-08-08 04:18 UTC
How can I enter the client secret contain dash sign? The pac command treat '-' as an argument. It say "An unknown argument -aaakkd******************************" was passed.

pac auth create --name MyOrg-SPN --applicationId 00000000-0000-0000-0000-000000000000 --clientSecret '-aaakkd******************************' --tenant 00000000-0000-0000-0000-000000000000

System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 13th Gen Intel(R) Core(TM) i7-1355U
    Memory: 17.23 GB / 39.68 GB
  Browsers:
    Edge: Chromium (123.0.2420.97)
    Internet Explorer: 11.0.19041.4355

**Comment by petrochuk** [comment] 2024-08-08 12:57
Closed as duplicate of #987

**Closed by petrochuk** 2024-08-08 12:57 UTC
Labels: bug
