### ISSUE TITLE
Import-Solution errors out with expired access token after 60 min

### ISSUE THREAD

**Issue by viacheslav-protsenko** [microsoft/powerplatform-build-tools#180] opened 2022-08-23 14:05 UTC
Hello. I have a big solution that needs to be installed on the environment. An error occurred while importing the solution, the logs are below. 
![image](https://user-images.githubusercontent.com/30999536/186177984-22588b40-bea0-43cf-a563-081bf4229110.png)

More precisely, the problem is related to asynchronous requests. An hour later, I received the error _### "The HTTP request is unauthorized with client authentication scheme 'Anonymous'"_, according to error, I can assume that the problem is in the token update. I would like to note that there was no such error when using the *.0 version

![image](https://user-images.githubusercontent.com/30999536/186179115-5071eaa9-6d20-441e-b2cb-411ea00ebfd5.png)

**Comment by tiemar** [comment] 2022-08-23 14:07
...same here in #179

**Comment by davidjenni** [comment] 2022-08-24 03:56
@viacheslav-protsenko this is likely a dupe to #179, as you already noted. This was fixed for this issue #139. Investigating on our end

**Comment by davidjenni** [comment] 2022-08-24 21:39
@viacheslav-protsenko since your task IS using appID/SPN, but the OP in #179 confirmed they are using username/pw authN, I don't think this is a dupe of #179, but likely related.
We're investigating...
AB#2894540

**Comment by davidjenni** [comment] 2022-08-29 18:00
@viacheslav-protsenko the fix has been released as PP-BT v2.0.5 to VS Marketplace; it should shortly propagate to the different AzDevOps orgs. Should this still repro, please do verify that the running task is indeed v 2.0.5

**Closed by davidjenni** 2022-08-29 18:00 UTC
Labels: bug
