### ISSUE TITLE
Deploy Package Task fail

### ISSUE THREAD

**Issue by saadnadir** [microsoft/powerplatform-build-tools#178] opened 2022-08-23 01:42 UTC
- Power PLatform Build Tool Extension Version : **2.0.4** 
- DevOps Pipeline Task : **Power Platform Deploy Package** 

Behavior: In Azure DevOps pipeline, i define Power Platform Deploy Package task with the following properties:

- Authentication type: Username/password (no MFA support)
- Environment Url: refering my target environment
- Package File: referencing the DLL to my deployment package.

In my deployment package, i import various power platform solutions, among those solutions there is one solution that contains **solution-aware dataflows**

I get the following error in the output of the solution history.

![issue deployment package](https://user-images.githubusercontent.com/39247752/186049057-8b8ace80-6143-4186-8442-e0c85b54fe5d.PNG)

I noticed that only Power Platform solutions that contains Dataflows are failing, as soon as i exclude the datafalows from my solutions it works. 

Also there is no helpful information in the pipeline logs.

![image](https://user-images.githubusercontent.com/39247752/186049429-3e9b72ea-e43e-42e7-813e-d273bd08f742.png)

I also notice that i am only capable of running the deployment with the Authentication type: **Username/password** and i cannot run it with **Service Principal/client secret** , otherwise i cannot see the dataflow appearing in the dataflow list. 

The deployment has to be done using an office 365 and not using app registration (application user), otherwise the dataflows are not display in the UI in https://make.powerapps.com.

**Comment by davidjenni** [comment] 2022-08-24 21:31
@saadnadir yes, known issue for now with solution import & deploy package for solutions that contain Flows: Flows require the importing user to be username/password. The PowerAutomate side has no support yet when the importing "user" is an an AppUser, the Flow inherits the calling user as owner. We have work underway to mitigate that from our pac CLI/task side, but that work has not finished yet.
Unfortunately, this is for now "by design", as unsatisfying this is.

**Comment by saadnadir** [comment] 2022-08-24 21:38
@davidjenni i am not refering to power automate flows within a solution in my issue. 
I refer to **Data Flow** component. 

When a solution includes **Data Flow**, Deploy Package task of the Power Platform Build Tool extension fails to import the deployment package. 

@davidjenni can you reopen and confirm my issue please ?

**Comment by davidjenni** [comment] 2022-08-24 22:02
@saadnadir thanks for clarifying, reopening the issue.

there seem several issues and follow-ups here:
1. the first screenshot (with the solution history from the web UI) shows a conn timeout error within the MS.Mashup.Web.DataFlow.CrmPlugin; our team has little to no insight on why that MSFT-owned plugin needs that much time?
2. AzDO log has not all the details:
That's correct and in part by design: The PackageDeploy (PD) library that the task (and pac CLI) is using does create a rather verbose log, hence we don't dump it into the regular AzDO log.
The first yellow message from within that PD library does point out to "check the log file". The DeployPackage PP-BT task does indeed save away that log file:
if your pipeline is a Build pipeline, it is uploaded to the build job's artifact store;
if you're running as a release pipeline, it is part of the "Download All Logs" on the Logs page of the rel pipeline run
![image](https://user-images.githubusercontent.com/3200210/186531476-a34cc56b-d864-4e11-b762-60db93f9ce97.png)

**Comment by saadnadir** [comment] 2022-08-24 22:33
@davidjenni After reading the logs, it turns out the same error that is mentionned in the solution history web UI.

It looks like that the timeout issue of the MSFT-owned plugin **Microsoft.Mashup.Web.Dataflow.CrmPlugin.Plugin**  is causing the pipeline to fails after 2 minutes of execution.

How can i fix this issue in this case ? 

i noticed that this plugin is invoked only when the solution we import with the deploy package task contains a dataflow. When i remove the dataflow from the solution, everything works fine. I also tried to use a dummy dataflow and its causing the same issue.

Any chance tha this issuet can be taking care of by your team? 

![image](https://user-images.githubusercontent.com/39247752/186534054-1adc9b82-7869-496d-8dbb-b744033a7d7c.png)

**Comment by davidjenni** [comment] 2022-08-25 00:30
@saadnadir our team has zero insight or expertise into that plugin, our task is just the bearer of bad news, sorry. Best approach is to go through MSFT support to have this routed to the proper owners within MSFT. It's out of scope for my team, sorry.

**Closed** 2022-08-29 17:57 UTC
