### ISSUE TITLE
PAC Auth Issue - App Id and Client Secret

### ISSUE THREAD

**Issue by just-marc-stevenson** [microsoft/powerplatform-build-tools#766] opened 2024-02-26 12:34 UTC
When using an APP Id/Client Secret to create a auth profile we regularly run into an issue where it reports that the profile has expired:

![image](https://github.com/microsoft/powerplatform-build-tools/assets/142887018/528d3bb3-2e4c-4acd-acaa-e69fc83eeace)

Once this happens when you try to do **any** pac command, including listing or attempting to delete the profile you get the error, meaning it can't be fixed through the CLI. Only option is to delete the authprofiles.json file manually.

![image](https://github.com/microsoft/powerplatform-build-tools/assets/142887018/e339f3b0-25af-4733-a88a-87131cfe9e8a)

**Comment by tehcrashxor** [comment] 2024-02-28 19:17
Duplicate of #731

That issue shipped in the version of PAC you're using (v1.30.4), and was fixed in v1.30.5 and up

**Closed by tehcrashxor** 2024-02-28 19:17 UTC
