### ISSUE TITLE
Error: AuthProfileUseExpired

### ISSUE THREAD

**Issue by parvezghumra** [microsoft/powerplatform-build-tools#729] opened 2024-01-30 10:04 UTC
Currently getting this error using version 1.30.4 and 1.30.3 of PAC CLI. Earlier versions seem ok

![image](https://github.com/microsoft/powerplatform-build-tools/assets/8039551/5f0950c2-6be1-433e-9c96-4f286fa71ddd)

Log files attached
[pac-log.txt](https://github.com/microsoft/powerplatform-build-tools/files/14096052/pac-log.txt)
[pac-log.txt](https://github.com/microsoft/powerplatform-build-tools/files/14096056/pac-log.txt)

**Comment by joem-msft** [comment] 2024-01-31 19:00
Thank you for reporting this issue. The issue is understood and we're working on getting a fix and patch out.

**Comment by tehcrashxor** [comment] 2024-01-31 23:53
Fixed with the release of PAC v1.30.5

**Closed by tehcrashxor** 2024-01-31 23:53 UTC
Labels: bug
