### ISSUE TITLE
Publish-pipeline-artifact fails with CLI for managed solution but still okay with Powershell

### ISSUE THREAD

**Issue by rcatbp** [microsoft/powerplatform-build-tools#216] opened 2022-10-12 15:47 UTC
Pipeline worked for 9 months then upgraded from Power shell to CLI.
Now publish only works for Unmanaged but fails for managed I raised a full ticket here
https://developercommunity.visualstudio.com/t/Publish-Pipeline-Artifact-Power-Platfor/10170869
If I untick the 'managed' box it worked, how weird is that?
Now reverted back to Powershell and all okay but I have no hair left.
Cheers, Richard

![publish-pipeline-artifact-fails](https://user-images.githubusercontent.com/96841324/195388686-f8e5b06f-3b2e-452f-b150-96b4010d4d0e.png)

[Summary-Unmanaged-okay-managed-fails.txt](https://github.com/microsoft/powerplatform-vscode/files/9766607/Summary-Unmanaged-okay-managed-fails.txt)

**Comment by davidjenni** [comment] 2022-10-18 23:13
@rcatbp Looking at your .txt file, the Publish task fails since it cannot find the just-exported `D:\\a\\1\\a\\PADCompliance-Managed.zip` file. We had a bug in the underlying pac CLI that resulted for managed exports to add an extra "_managed" to the base name (resulting in your example with this file on disk: `PADCompliance-Managed_managed.zip`).

The upcoming refresh (ETA later this week) will have this regression fixed; in the meantime, change your "publish managed.zip" task to use either a wild card for the artifact input name, or add the extra _managed, as above.

AB#2925297

**Comment by davidjenni** [comment] 2022-10-20 22:27
Fixed with 2.0.8; note that due to Azure DevOps's caching, it might take several hours until all build agents run with the latest update

https://github.com/microsoft/powerplatform-build-tools/releases/tag/v2.0.8

CC: @rcatbp

**Closed by davidjenni** 2022-10-20 22:27 UTC
Labels: bug
