### ISSUE TITLE
An unknown argument When create authentication using Service Principal

### ISSUE THREAD

**Issue by hoangducdev** [microsoft/powerplatform-build-tools#988] opened 2024-08-08 04:08 UTC
### Discussed in https://github.com/microsoft/powerplatform-build-tools/discussions/987

<div type='discussions-op-text'>

<sup>Originally posted by **hoangducdev** August  8, 2024</sup>
How can I enter the client secret contain dash sign? The pac command treat '-' as an argument. It say "An unknown argument -aaakkd******************************" was passed.

pac auth create --name MyOrg-SPN --applicationId 00000000-0000-0000-0000-000000000000 --clientSecret '-aaakkd******************************' --tenant 00000000-0000-0000-0000-000000000000</div>

**Comment by petrochuk** [comment] 2024-08-08 12:56
Closed as duplicate of #987

**Closed by petrochuk** 2024-08-08 12:56 UTC
