### ISSUE TITLE
pac auth select returns wrong "Kind" in non interactive mode

### ISSUE THREAD

**Issue by prohannes** [microsoft/powerplatform-build-tools#753] opened 2024-02-15 09:44 UTC
## History of changes in behavior:
always the same environment

### Version: 1.29.11+g9e2b163
`{"Status":"Success","Errors":[],"Warnings":[],"Information":["Input commands: [\"auth\",\"select\"]","New default profile:"],"Results":[{"Index":0,"IsActive":true,"Kind":"DATAVERSE"`

**"Kind":"DATAVERSE"**

### Version: 1.30.5+g0bf9504
`{"Status":"Success","Errors":[],"Warnings":[],"Information":["Input commands: [\"auth\",\"select\"]","New default profile:"],"Results":[{"Index":0,"IsActive":true,"Kind":{}`

**"Kind":{}**

### Version: 1.30.7+ge6211cf
`{"Status":"Success","Errors":[],"Warnings":[],"Information":["Input commands: [\"auth\",\"select\"]","New default profile:"],"Results":[{"Index":0,"IsActive":true,"Kind":"UNIVERSAL"`

**"Kind":"UNIVERSAL"**

## Expected

-  **"Kind":"DATAVERSE"**

but now **"Kind":"UNIVERSAL"** is returned
UNIVERSAL should be returned when no url/enviroment is given

**Comment by tehcrashxor** [comment] 2024-02-16 21:13
Change is by design, as a step from deprecating the entire concept of Auth Profile Kinds.

Excerpt from the [v1.30.6 release notes](https://www.nuget.org/packages/Microsoft.PowerApps.CLI/#releasenotes-body-tab):

### 1.30.6
 Affects all verbs:
 - The current Universal auth profile will now be selected before falling back on previous logic for the Dataverse and Admin auth profile kinds.
   This means that old profiles will never be used if there is an existing Universal profile.
   In the future, these old profiles will no longer be supported. Please create new profiles (which will be Universal) and set the --environment argument or 'pac org select' to set the active Dataverse environment for the profile.
 - All verbs that interact with Dataverse now support the `--environment` argument.
   This argument allows the user to explicitly override the active environment for the current profile.
   For most verbs this argument is optional, as it will fall back to the active environment for the current profile.
   Only when a verb will potentially corrupt or change security policies will these arguments be required to be specified. (e.g. pac admin copy, pac admin delete)

auth
 - Deprecation of all but the Universal auth kinds. The `--kind` argument for `pac auth create` is now officially ignored. All new authentication profiles will use the Universal auth kind.
 - auth create argument `--url` is now deprecated, replaced with `--environment`. While `--url` supports only a url, the `--environment` argument supports organization id, environment id, and name searches. Other than the kinds of values allowed, these two argument behave the same.

--------

The lack of the kinds coming across in the 1.30.5 and 1.30.6 builds was due to a serialization error from the other changes.  It was fixed in 1.30.7 to return the profile's kind along with the other regression fixes, but looks like that missed the release notes.

**Closed by tehcrashxor** 2024-02-16 21:13 UTC
