### ISSUE TITLE
Need JSON output support for all thePAC CLI  commands

### ISSUE THREAD

**Issue by vignaesh01** [microsoft/powerplatform-build-tools#893] opened 2024-05-23 03:53 UTC
Need JSON output support for all the PAC CLI commands. If I am building a tooling on top of PAC CLI commands, it becomes very difficult to parse the command line output. Providing a JSON output will greatly help.

**Comment by rajyraman** [comment] 2024-05-23 04:05
See also https://github.com/microsoft/powerplatform-vscode/discussions/323

**Comment by tehcrashxor** [comment] 2024-05-29 23:47
Duplicate of discussion https://github.com/microsoft/powerplatform-build-tools/discussions/463

**Closed by tehcrashxor** 2024-05-29 23:47 UTC
